version: '3.5'

services:
  postgres:
    container_name: blog-service
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5433"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
